# Generated by Django 2.2.4 on 2019-10-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('look', models.IntegerField(choices=[(1, 'cool'), (2, 'cute'), (3, 'romantic')])),
                ('data', models.TextField(max_length=5000)),
            ],
        ),
    ]
